// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQd3EDieasn95NlvI7dFcl2q5YoJHN1Og',
    appId: '1:654393750018:web:e31e34f5a9f76226f7ed1b',
    messagingSenderId: '654393750018',
    projectId: 'usdinfra-a11c2',
    authDomain: 'usdinfra-a11c2.firebaseapp.com',
    storageBucket: 'usdinfra-a11c2.firebasestorage.app',
    measurementId: 'G-3P88VYSE9M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCSUpmbk_iGfBtfW6has_8Uy7S0zGNiT5s',
    appId: '1:654393750018:android:7f3f611aadd3782df7ed1b',
    messagingSenderId: '654393750018',
    projectId: 'usdinfra-a11c2',
    storageBucket: 'usdinfra-a11c2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRhDbV_m_rryhqDlYV-MgcyjrcIPLg6gk',
    appId: '1:654393750018:ios:0ae27a51017d75a8f7ed1b',
    messagingSenderId: '654393750018',
    projectId: 'usdinfra-a11c2',
    storageBucket: 'usdinfra-a11c2.firebasestorage.app',
    iosBundleId: 'com.example.usdinfra',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRhDbV_m_rryhqDlYV-MgcyjrcIPLg6gk',
    appId: '1:654393750018:ios:0ae27a51017d75a8f7ed1b',
    messagingSenderId: '654393750018',
    projectId: 'usdinfra-a11c2',
    storageBucket: 'usdinfra-a11c2.firebasestorage.app',
    iosBundleId: 'com.example.usdinfra',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQd3EDieasn95NlvI7dFcl2q5YoJHN1Og',
    appId: '1:654393750018:web:4c1ad3172c6ba35ef7ed1b',
    messagingSenderId: '654393750018',
    projectId: 'usdinfra-a11c2',
    authDomain: 'usdinfra-a11c2.firebaseapp.com',
    storageBucket: 'usdinfra-a11c2.firebasestorage.app',
    measurementId: 'G-7CK8C36N4F',
  );
}
